satellite_rhn_connect: "{{ lookup('env', 'SATELLITE_RHN_CONNECT') }}"
satellite_admin_username: "{{ lookup('env', 'SATELLITE_USERNAME') }}"
satellite_admin_password: "{{ lookup('env', 'SATELLITE_PASSWORD') }}"
satellite_organization:  "{{ lookup('env', 'SATELLITE_ORGANIZATION') }}"
satellite_location: "{{ lookup('env', 'SATELLITE_LOCATION') }}"
satellite_server_url: "https://{{ ansible_fqdn }}"
satellite_fw_service_name: RH-Satellite-6
satellite_apypie_rpm: "python2-apypie-0.2.1-2.el7.noarch.rpm"

# satellite install role options:
satellite_options: >-
  --foreman-initial-admin-username "{{ satellite_admin_username }}"
  --foreman-initial-admin-password "{{ satellite_admin_password }}"
  --foreman-initial-organization  "{{ satellite_organization }}"
  --foreman-initial-location  "{{ satellite_location }}"
  --foreman-proxy-dns-managed false
  --foreman-proxy-dns false
  --foreman-proxy-dhcp false
  --foreman-proxy-dhcp-managed false
  --foreman-proxy-tftp false
  --foreman-proxy-tftp-managed false
