driver:
  name: docker
platforms:
  - name: satellite_config
    image: centos:7
    ## Remove 'image' above and uncomment the following to run systemd in Docker
    # image: centos/systemd
    # privileged: true
    # command: /usr/lib/systemd/systemd --system
    # volumes:
    #   - /sys/fs/cgroup:/sys/fs/cgroup:ro
