---
- name: Pull down manifest
  get_url:
    url: >-
      https://subscription.rhsm.redhat.com/subscription/consumers/
      {{ manifest_uuid }}/export
    username: "{{ lookup('env', 'RHN_USER') }}"
    password: "{{ lookup('env', 'RHN_PASSWORD') }}"
    dest: /opt/satellite_manifest.zip
    validate_certs: no
  when: rhn_connect != 'disconnect'

- name: Copy manifest from local system to remote target
  copy:
    src: "{{ lookup('env', 'SATELLITE_MANIFEST') }}"
    dest: /opt/satellite_manifest.zip
    owner: root
    group: root
    mode: 0640
  when: rhn_connect == 'disconnect'

- name: "Upload the manifest"
  theforeman.foreman.katello_manifest:
    username: "{{ lookup('env','FOREMAN_USER') }}"
    password: "{{ lookup('env','FOREMAN_PASSWORD') }}"
    server_url: "https://{{ ansible_fqdn }}"
    organization: "{{ foreman_initial_organization }}"
    state: present
    manifest_path: "/opt/satellite_manifest.zip"
